[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="catalyst_lib"
path="src/lib.rs"

[[bin]]
name="catalyst"
path="src/main.rs"

[workspace]
members = [
    "lexer",
    "parser",
    "typec",
    "modules",
    "instance",
    "gen",
    "cli",
    "errors",
]

[profile.release]
debug = true

[features]
logging = ["log", "env_logger"]

[dependencies]
log = { version = "0.4", optional = true }
env_logger = { version = "0.9.0", optional = true }
cranelift-entity = "0.82.1"
cranelift-codegen = "0.82.1"
cranelift-frontend = "0.82.1"
cranelift-module = "0.82.1"
cranelift-object = "0.82.1"
cranelift-native = "0.82.1"
target-lexicon = "0.12.3"

lexer = { path = "lexer" }
errors = { path = "errors" }
parser = { path = "parser" }
modules = { path = "modules" }
typec = { path = "typec" }
instance = { path = "instance" }
gen = { path = "gen" }
cli = { path = "cli" }