[package]
name = "meta_mach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="meta_mach_lib"
path="src/lib.rs"

[[bin]]
name="meta_mach"
path="src/main.rs"

[workspace]
members = [
    "lexer",
    "parser",
    "typec",
    "modules",
    "instance",
    "gen",
]

[dependencies]
lexer = { path = "lexer" }
parser = { path = "parser" }
typec = { path = "typec" }
modules = { path = "modules" }
instance = { path = "instance" }
gen = { path = "gen" }