[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="catalyst_lib"
path="src/lib.rs"

[[bin]]
name="catalyst"
path="src/main.rs"

[workspace]
members = [
    "storage",
    "lexer",
    "lexer_types",
    "parser",
    "ast",
    "typec",
    "typec_types",
    "modules",
    "module_types",
    "instance",
    "instance_types",
    "gen",
    "incr",
    "cli",
    "errors",
]

[profile.release]
#debug = true

[dependencies]
cranelift-codegen = "0.82.1"
cranelift-frontend = "0.82.1"
cranelift-module = "0.82.1"
cranelift-object = "0.82.1"
cranelift-native = "0.82.1"
target-lexicon = "0.12.3"
cc = "1.0.73"
num_cpus = "1.13.1"

lexer = { path = "lexer" }
lexer_types = { path = "lexer_types" }
errors = { path = "errors" }
parser = { path = "parser" }
ast = { path = "ast" }
modules = { path = "modules" }
module_types = { path = "module_types" }
typec = { path = "typec" }
typec_types = { path = "typec_types" }
instance = { path = "instance" }
instance_types = { path = "instance_types" }
gen = { path = "gen" }
cli = { path = "cli" }
storage = { path = "storage" }
incr = { path = "incr" }