[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "utils/ansi-coloring",
    "utils/storage",
    "utils/errors",
    "utils/cli",
    "utils/state",
    "utils/graphs",
    "utils/scope",

    "types/diags",
    "types/lexing-t",
    "types/packaging-t",
    "types/parsing-t",
    "types/type-checking-t",

    "stages/lexing",
    "stages/parsing",
    "stages/packaging",
    "stages/type-checking",
]

[dependencies]
