[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "catalystc"
path = "src/main.rs"

[workspace]
exclude = [
    "state",
]

members = [
    "storage",
    "lexer",
    "parser",
    "ast",
    "typec",
    "typec_types",
    "modules",
    "module_types",
    "instance",
    "instance_types",
    "gen",
    "incr",
    "cli",
    "errors",
    "matching",
    "ownership",
    "lifetimes",
    "core",
]

[dependencies]
core = { path = "core" }
storage = { path = "storage" }