//! Crate split form `lexing-t` to isolate code generated by `logos`.
//! The [`TokenKind`] is used only when parsing.

mod lexer;
mod token;

pub use lexer::Lexer;
pub use token::{Token, TokenKind, EQUAL_SIGN_PRECEDENCE};
