#![feature(unboxed_closures)]
#![feature(fn_traits)]
#![feature(is_sorted)]

//! Crate split form `span` to isolate code generated by `logos`.
//! The [`TokenKind`] is used only when parsing.

mod ctl;
mod lexer;
mod token;

pub use {
    ctl::ctl_lexer_next,
    lexer::Lexer,
    logos::Logos,
    span::*,
    token::{
        NoTokenMeta, SkippedToken, SourceInfo, Token, TokenKind, TokenMeta, EQUAL_SIGN_PRECEDENCE,
    },
};
