[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexing-t = { version = "0.1.0", path = "../../types/lexing-t" }
mir-t = { version = "0.1.0", path = "../../types/mir-t" }
packaging-t = { version = "0.1.0", path = "../../types/packaging-t" }
storage = { version = "0.1.0", path = "../../utils/storage" }
diags = { version = "0.1.0", path = "../../types/diags" }
typec-t = { version = "0.1.0", path = "../../types/typec-t" }
lexing = { version = "0.1.0", path = "../../stages/lexing" }


rkyv = { version = "0.7.39", features = ["copy"] }
region = "3.0.0"
target-lexicon = "0.12.4"
object = { version = "0.29.0", default-features = false, features = ["write"] }
cc = "1.0.73"
windows-sys = { version = "0.42.0", features = ["Win32", "Win32_Foundation", "Win32_System_LibraryLoader"] }
cranelift-codegen = { version = "0.92.0" }
cranelift-frontend = "0.92.0"
libc = "0.2.139"
typec-u = { version = "0.1.0", path = "../../utils/typec-u" }
