[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
bitflags = "1.3.2"
bump-alloc = { version = "0.1.0", path = "../bump-alloc" }
dashmap = "5.4.0"

[dev-dependencies]
rmp-serde = "1.1.0"
