[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
entities = { version = "0.1.0", package = "catalyst_entities", path = "../entities" }
rkyv = { version = "0.7.39", features = ["copy"] }
