[package]
name = "snippet-display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annotate-snippets = { version = "0.9.1", features = ["color"] }
diags = { version = "0.1.0", path = "../../types/diags" }
resources = { version = "0.1.0", path = "../../types/resources" }
span = { version = "0.1.0", path = "../../types/span" }
storage = { version = "0.1.0", path = "../storage" }
