[package]
name = "type-creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
span = { version = "0.1.0", path = "../../types/span" }
resources = { version = "0.1.0", path = "../../types/resources" }
storage = { version = "0.1.0", path = "../storage" }
types = { version = "0.1.0", path = "../../types/types" }
