[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-codegen = "0.82.1"
cranelift-frontend = "0.82.1"
cranelift-module = "0.82.1"

instance_types = { path = "../instance_types" }
storage = { path = "../storage" }
typec_types = { path = "../typec_types" }
lexer_types = { path = "../lexer_types" }