[package]
name = "cc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
middleware = { path = "../middleware" }
cli = { path = "../../utils/cli" }
cc = "1.0.73"

