[package]
name = "lexing-t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-coloring = { path = "../../utils/ansi-coloring" }
storage = { path = "../../utils/storage" }

