[package]
name = "lexing-t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

storage = { path = "../../utils/storage" }
serde = { version = "1", features = ["derive"] }
