[package]
name = "type-checking-t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storage = { path = "../../utils/storage" }
lexing-t = { path = "../lexing-t" }
parsing-t = { path = "../parsing-t" }
packaging-t = { path = "../packaging-t" }