[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diags = { path = "../../types/diags" }
packaging-t = { path = "../../types/packaging-t" }

fmt = { path = "../../subcommands/fmt" }
storage = { path = "../../utils/storage" }
snippet-display = { path = "../../utils/snippet-display" }
packaging = { path = "../../stages/packaging" }
lexing-t = { path = "../../types/lexing-t" }
