[package]
name = "bump-alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
region = "3.0.0"
serde = { version = "1", features = ["derive", "rc"] }
dashmap = "5.4.0"
smallvec = { version = "1.10.0", features = ["union"] }
arc-swap = { version = "1.5.1", features = ["serde"] }

[features]
default = ["dashmap/serde", "smallvec/serde", "arc-swap/serde"]