[package]
name = "bump-alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
region = "3.0.0"
serde = { version = "1", features = ["derive"] }