[package]
name = "bump-alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
region = "3.0.0"
dashmap = "5.4.0"
smallvec = { version = "1.10.0" }
arc-swap = { version = "1.5.1" }
rkyv = { version = "0.7.39", features = ["copy"] }

[features]
default = ["rkyv/validation", "rkyv/copy", "smallvec/union"]